### ISSUE TITLE
FAT V1.0 - Make reusable buttons

### ISSUE THREAD

**Issue by kristijanfistrek** [CodeITLab/fit_track_frontend_app#57]
Make reusable buttons using this principle: https://vuejs.org/guide/components/props.html

It is important to make a reusable button component with the main css class (example: main-btn) which has the unified width, height, font stylings. We should enable the the passing of at least two props which would be the css classes for styling.

**TODO**: 

- [x] Under src/components create a separate folder called "buttons"
- [x] Inside it, create a file called Button.vue
- [x] Create 3 Vue sections that every component needs (pogledaj kako smo to drugdje definirali):
1. script
2. template
3. style

- Create and pass 3 props for the button
- [x] backgroundColor
- [x] borderColor
- [x] text
